
######################################################################

run:
	@echo "Start compile"
	g++ main.cpp -o my_program
	@echo "Start exe"
	./my_program
clean:
	rm my_program output1_flip.bmp output2_flip.bmp